baseURL = 'https://ikesau.co'
languageCode = 'en-ca'
title = 'ikesau.co'
theme = 'ikesau'

[taxonomies]
  tag = "tags"
[params]
    description = 'The website of Ike Saunders'

permalinks.blog = "/:section/:title/"

[outputs]
  home = ['html', 'rss', 'atom']

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.atom]
    mediaType = "application/atom+xml"
    baseName = "feed"
    isPlainText = true

[frontmatter]
date = [ "date", ":filename" ]
