baseURL = 'https://ikesau.co'
languageCode = 'en-ca'
title = 'ikesau.co'
theme = 'ikesau'

[taxonomies]
  tag = "tags"
[params]
    description = 'The website of Ike Saunders'

permalinks.blog = "/:section/:title/"

[outputs]
  home = ['html', 'rss']

[frontmatter]
date = [ "date", ":filename" ]
